<a href="https://colab.research.google.com/github/GinaldoDSSilva/ImersaoPythonAula/blob/main/Imersao_Python_aula_02_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aula 2 - Importação

importando biblioteca pandas

In [61]:
import pandas as pd
import plotly.express as px

carregando tabela principal e guardando em variavel dataframe

In [62]:
df_principal = pd.read_excel("/content/acoes_puras.xlsx", sheet_name="Principal")
df_principal

,Ativo,Data,Último (R$),Var. Dia (%),Var. Sem. (%),Var. Mês (%),Var. Ano (%),Var. 12M (%),Val. Mín,Val. Máx,...,Variação $.1,Resultado.2,Variação Ano %,Valor Inicial (R$).3,Variação $.2,Resultado.3,Variação 12M %,Valor Inicial (R$).4,Variação $.3,Resultado.4
0,USIM5,2024-01-26,9.50,5.20,11.76,2.26,2.26,15.97,9.18,9.56,...,108151480.40,Subiu,0.02,9.29,108151480.40,Subiu,0.16,8.19,673890100.70,Subiu
1,CMIN3,2024-01-26,6.82,2.40,2.40,-12.11,-12.11,50.56,6.66,6.86,...,-1043592200.00,Desceu,-0.12,7.76,-1043592200.00,Desceu,0.51,4.53,2543452344.00,Subiu
2,PETR3,2024-01-26,41.96,2.19,7.73,7.64,7.64,77.55,40.81,42.34,...,7087772680.00,Subiu,0.08,38.98,7087772680.00,Subiu,0.78,23.63,43616542549.00,Subiu
3,SUZB3,2024-01-26,52.91,2.04,2.14,-4.89,-4.89,18.85,51.89,53.17,...,-1859212322.00,Desceu,-0.05,55.63,-1859212322.00,Desceu,0.19,44.52,5735330905.00,Subiu
4,CPFE3,2024-01-26,37.10,2.03,2.49,-3.66,-3.66,20.70,36.37,37.32,...,-264598820.90,Desceu,-0.04,38.51,-264598820.90,Desceu,0.21,30.74,1194473548.00,Subiu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-9.47,-13.98,-13.98,-32.72,10.70,11.08,...,-929460216.60,Desceu,-0.14,12.45,-929460216.60,Desceu,-0.33,15.92,-2781316323.00,Desceu
77,BHIA3,2024-01-26,8.70,-2.46,-6.95,-23.55,-23.55,-85.74,8.67,8.95,...,-254178125.40,Desceu,-0.24,11.38,-254178125.40,Desceu,-0.86,61.01,-4961222496.00,Desceu
78,RENT3,2024-01-26,56.24,-3.63,-6.41,-11.57,-11.57,-2.77,56.04,58.90,...,-6278141320.00,Desceu,-0.12,63.60,-6278141320.00,Desceu,-0.03,57.84,-1367026195.00,Desceu
79,CVCB3,2024-01-26,3.07,-4.36,-5.54,-12.29,-12.29,-36.83,3.05,3.23,...,-226090475.70,Desceu,-0.12,3.50,-226090475.70,Desceu,-0.37,4.86,-940741575.30,Desceu
80,GOLL4,2024-01-26,5.92,-8.07,-15.91,-34.00,-34.00,-25.44,5.51,6.02,...,-604403916.40,Desceu,-0.34,8.97,-604403916.40,Desceu,-0.25,7.94,-400316504.60,Desceu

In [63]:
df_Total_de_acoes = pd.read_excel("/content/acoes_puras.xlsx", sheet_name="Total_de_acoes")
df_Total_de_acoes

                      Código  Qtde. Teórica
0                      RRRP3   235665566.00
1                      ALOS3   532616595.00
2                      ALPA4   176733968.00
3                      ABEV3  4394245879.00
4                      ARZZ3    62305891.00
..                       ...            ...
84                     VBBR3  1114412532.00
85                     WEGE3  1481593024.00
86                     YDUQ3   289347914.00
87  Quantidade Teórica Total 96372098181.00
88                   Redutor    17047850.79

[89 rows x 2 columns]

In [64]:
df_Ticker = pd.read_excel("/content/acoes_puras.xlsx", sheet_name="Ticker")
df_Ticker

    Ticker            Nome
0    MGLU3  Magazine Luiza
1    HAPV3         Hapvida
2    PETR4       Petrobras
3    B3SA3              B3
4    USIM5        Usiminas
..     ...             ...
530  TKNO3           Tekno
531  COCE6          Coelce
532  MGEL3         Mangels
533  CTSA8      Santanense
534  MMAQ4   Minasmáquinas

[535 rows x 2 columns]

In [65]:
df_chatgpt = pd.read_excel("/content/acoes_puras.xlsx", sheet_name="chatgpt")
df_chatgpt

     Nome da Empresa                 Segmento  Idade (anos)
0           Usiminas  Siderurgia e Metalurgia            62
1      CSN Mineração                Mineração            78
2          Petrobras           Petróleo e Gás            71
3             Suzano         Papel e Celulose           100
4       CPFL Energia                  Energia           111
..               ...                      ...           ...
73  Carrefour Brasil                   Varejo            49
74       Casas Bahia                   Varejo            72
75          Localiza      Locação de Veículos            51
76               CVC                  Turismo            52
77               GOL                  Aviação            24

[78 rows x 3 columns]

utilizando apenas as primeiras 4 colunas no df_principal

In [66]:
df_principal = df_principal[['Ativo', 'Data', 'Último (R$)', 'Var. Dia (%)']].copy()
df_principal

    Ativo       Data  Último (R$)  Var. Dia (%)
0   USIM5 2024-01-26         9.50          5.20
1   CMIN3 2024-01-26         6.82          2.40
2   PETR3 2024-01-26        41.96          2.19
3   SUZB3 2024-01-26        52.91          2.04
4   CPFE3 2024-01-26        37.10          2.03
..    ...        ...          ...           ...
76  CRFB3 2024-01-26        10.71         -2.45
77  BHIA3 2024-01-26         8.70         -2.46
78  RENT3 2024-01-26        56.24         -3.63
79  CVCB3 2024-01-26         3.07         -4.36
80  GOLL4 2024-01-26         5.92         -8.07

[81 rows x 4 columns]

renomeando as colunas no df_principal

In [67]:
df_principal = df_principal.rename(columns={'Último (R$)':'valor_final','Var. Dia (%)': 'var_dia_pct'}).copy()
df_principal

    Ativo       Data  valor_final  var_dia_pct
0   USIM5 2024-01-26         9.50         5.20
1   CMIN3 2024-01-26         6.82         2.40
2   PETR3 2024-01-26        41.96         2.19
3   SUZB3 2024-01-26        52.91         2.04
4   CPFE3 2024-01-26        37.10         2.03
..    ...        ...          ...          ...
76  CRFB3 2024-01-26        10.71        -2.45
77  BHIA3 2024-01-26         8.70        -2.46
78  RENT3 2024-01-26        56.24        -3.63
79  CVCB3 2024-01-26         3.07        -4.36
80  GOLL4 2024-01-26         5.92        -8.07

[81 rows x 4 columns]

adicionando coluna calculando valor _inicial
inicial = final/ 1 + var_dia_pct

In [68]:
df_principal['var_dia_pct'] = df_principal['var_dia_pct']/100
df_principal['valor_inicial'] = df_principal['valor_final'] / (df_principal['var_dia_pct'] + 1)
df_principal

    Ativo       Data  valor_final  var_dia_pct  valor_inicial
0   USIM5 2024-01-26         9.50         0.05           9.03
1   CMIN3 2024-01-26         6.82         0.02           6.66
2   PETR3 2024-01-26        41.96         0.02          41.06
3   SUZB3 2024-01-26        52.91         0.02          51.85
4   CPFE3 2024-01-26        37.10         0.02          36.36
..    ...        ...          ...          ...            ...
76  CRFB3 2024-01-26        10.71        -0.02          10.98
77  BHIA3 2024-01-26         8.70        -0.02           8.92
78  RENT3 2024-01-26        56.24        -0.04          58.36
79  CVCB3 2024-01-26         3.07        -0.04           3.21
80  GOLL4 2024-01-26         5.92        -0.08           6.44

[81 rows x 5 columns]

fazendo merge df_principal com df_Total_de_acoes
em comum ativo e código, informação importante qrt teorica

In [69]:
df_principal = df_principal.merge(df_Total_de_acoes,left_on='Ativo',right_on='Código',how='left')
df_principal

,Ativo,Data,valor_final,var_dia_pct,valor_inicial,Código,Qtde. Teórica
0,USIM5,2024-01-26,9.50,0.05,9.03,USIM5,515117391.00
1,CMIN3,2024-01-26,6.82,0.02,6.66,CMIN3,1110559345.00
2,PETR3,2024-01-26,41.96,0.02,41.06,PETR3,2379877655.00
3,SUZB3,2024-01-26,52.91,0.02,51.85,SUZB3,683452836.00
4,CPFE3,2024-01-26,37.10,0.02,36.36,CPFE3,187732538.00
...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-0.02,10.98,CRFB3,533990587.00
77,BHIA3,2024-01-26,8.70,-0.02,8.92,BHIA3,94843047.00
78,RENT3,2024-01-26,56.24,-0.04,58.36,RENT3,853202347.00
79,CVCB3,2024-01-26,3.07,-0.04,3.21,CVCB3,525582771.00
80,GOLL4,2024-01-26,5.92,-0.08,6.44,GOLL4,198184909.00

retirando coluna codigo - pois esta duplicada

In [70]:
df_principal = df_principal.drop(columns='Código').copy()
df_principal

    Ativo       Data  valor_final  var_dia_pct  valor_inicial  Qtde. Teórica
0   USIM5 2024-01-26         9.50         0.05           9.03   515117391.00
1   CMIN3 2024-01-26         6.82         0.02           6.66  1110559345.00
2   PETR3 2024-01-26        41.96         0.02          41.06  2379877655.00
3   SUZB3 2024-01-26        52.91         0.02          51.85   683452836.00
4   CPFE3 2024-01-26        37.10         0.02          36.36   187732538.00
..    ...        ...          ...          ...            ...            ...
76  CRFB3 2024-01-26        10.71        -0.02          10.98   533990587.00
77  BHIA3 2024-01-26         8.70        -0.02           8.92    94843047.00
78  RENT3 2024-01-26        56.24        -0.04          58.36   853202347.00
79  CVCB3 2024-01-26         3.07        -0.04           3.21   525582771.00
80  GOLL4 2024-01-26         5.92        -0.08           6.44   198184909.00

[81 rows x 6 columns]

adicional coluna variacao_rs =  final - inicial vezes qtde teorica

In [71]:
df_principal['variacao_rs'] = (df_principal['valor_final']-df_principal['valor_inicial'])*df_principal['Qtde. Teórica']
df_principal

,Ativo,Data,valor_final,var_dia_pct,valor_inicial,Qtde. Teórica,variacao_rs
0,USIM5,2024-01-26,9.50,0.05,9.03,515117391.00,241889725.43
1,CMIN3,2024-01-26,6.82,0.02,6.66,1110559345.00,177515970.30
2,PETR3,2024-01-26,41.96,0.02,41.06,2379877655.00,2140059393.53
3,SUZB3,2024-01-26,52.91,0.02,51.85,683452836.00,722946282.71
4,CPFE3,2024-01-26,37.10,0.02,36.36,187732538.00,138573955.06
...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-0.02,10.98,533990587.00,-143635530.57
77,BHIA3,2024-01-26,8.70,-0.02,8.92,94843047.00,-20810240.84
78,RENT3,2024-01-26,56.24,-0.04,58.36,853202347.00,-1807432634.46
79,CVCB3,2024-01-26,3.07,-0.04,3.21,525582771.00,-73557408.06
80,GOLL4,2024-01-26,5.92,-0.08,6.44,198184909.00,-102993202.62

formatando valores como float - ponto flutuantes (com casas decimais)

In [72]:
pd.options.display.float_format = '{:.2f}'.format

formatando Qtde. Teórica como numero inteiro

In [73]:
df_principal['Qtde. Teórica'] = df_principal['Qtde. Teórica'].astype(int)
df_principal

,Ativo,Data,valor_final,var_dia_pct,valor_inicial,Qtde. Teórica,variacao_rs
0,USIM5,2024-01-26,9.50,0.05,9.03,515117391,241889725.43
1,CMIN3,2024-01-26,6.82,0.02,6.66,1110559345,177515970.30
2,PETR3,2024-01-26,41.96,0.02,41.06,2379877655,2140059393.53
3,SUZB3,2024-01-26,52.91,0.02,51.85,683452836,722946282.71
4,CPFE3,2024-01-26,37.10,0.02,36.36,187732538,138573955.06
...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-0.02,10.98,533990587,-143635530.57
77,BHIA3,2024-01-26,8.70,-0.02,8.92,94843047,-20810240.84
78,RENT3,2024-01-26,56.24,-0.04,58.36,853202347,-1807432634.46
79,CVCB3,2024-01-26,3.07,-0.04,3.21,525582771,-73557408.06
80,GOLL4,2024-01-26,5.92,-0.08,6.44,198184909,-102993202.62

renomeando coluna Qtde. Teórica para qtd_teorica

In [74]:
df_principal = df_principal.rename(columns={'Qtde. Teórica':'Qtd_teorica'}).copy()
df_principal

,Ativo,Data,valor_final,var_dia_pct,valor_inicial,Qtd_teorica,variacao_rs
0,USIM5,2024-01-26,9.50,0.05,9.03,515117391,241889725.43
1,CMIN3,2024-01-26,6.82,0.02,6.66,1110559345,177515970.30
2,PETR3,2024-01-26,41.96,0.02,41.06,2379877655,2140059393.53
3,SUZB3,2024-01-26,52.91,0.02,51.85,683452836,722946282.71
4,CPFE3,2024-01-26,37.10,0.02,36.36,187732538,138573955.06
...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-0.02,10.98,533990587,-143635530.57
77,BHIA3,2024-01-26,8.70,-0.02,8.92,94843047,-20810240.84
78,RENT3,2024-01-26,56.24,-0.04,58.36,853202347,-1807432634.46
79,CVCB3,2024-01-26,3.07,-0.04,3.21,525582771,-73557408.06
80,GOLL4,2024-01-26,5.92,-0.08,6.44,198184909,-102993202.62

adicionando coluna resultado
apply usa outras funcoes
lambda - funcao generica
em cada linha é aplicado a condicão if para classificação

In [75]:
df_principal['Resultado'] = df_principal['variacao_rs'].apply(lambda x: 'Subiu' if x > 0 else ('Desceu' if x < 0 else 'Estável'))
df_principal

,Ativo,Data,valor_final,var_dia_pct,valor_inicial,Qtd_teorica,variacao_rs,Resultado
0,USIM5,2024-01-26,9.50,0.05,9.03,515117391,241889725.43,Subiu
1,CMIN3,2024-01-26,6.82,0.02,6.66,1110559345,177515970.30,Subiu
2,PETR3,2024-01-26,41.96,0.02,41.06,2379877655,2140059393.53,Subiu
3,SUZB3,2024-01-26,52.91,0.02,51.85,683452836,722946282.71,Subiu
4,CPFE3,2024-01-26,37.10,0.02,36.36,187732538,138573955.06,Subiu
...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-0.02,10.98,533990587,-143635530.57,Desceu
77,BHIA3,2024-01-26,8.70,-0.02,8.92,94843047,-20810240.84,Desceu
78,RENT3,2024-01-26,56.24,-0.04,58.36,853202347,-1807432634.46,Desceu
79,CVCB3,2024-01-26,3.07,-0.04,3.21,525582771,-73557408.06,Desceu
80,GOLL4,2024-01-26,5.92,-0.08,6.44,198184909,-102993202.62,Desceu

In [76]:
df_principal = df_principal.merge(df_Ticker, left_on='Ativo', right_on='Ticker', how='left')
df_principal = df_principal.drop(columns=['Ticker'])
df_principal

,Ativo,Data,valor_final,var_dia_pct,valor_inicial,Qtd_teorica,variacao_rs,Resultado,Nome
0,USIM5,2024-01-26,9.50,0.05,9.03,515117391,241889725.43,Subiu,Usiminas
1,CMIN3,2024-01-26,6.82,0.02,6.66,1110559345,177515970.30,Subiu,CSN Mineração
2,PETR3,2024-01-26,41.96,0.02,41.06,2379877655,2140059393.53,Subiu,Petrobras
3,SUZB3,2024-01-26,52.91,0.02,51.85,683452836,722946282.71,Subiu,Suzano
4,CPFE3,2024-01-26,37.10,0.02,36.36,187732538,138573955.06,Subiu,CPFL Energia
...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-0.02,10.98,533990587,-143635530.57,Desceu,Carrefour Brasil
77,BHIA3,2024-01-26,8.70,-0.02,8.92,94843047,-20810240.84,Desceu,Casas Bahia
78,RENT3,2024-01-26,56.24,-0.04,58.36,853202347,-1807432634.46,Desceu,Localiza
79,CVCB3,2024-01-26,3.07,-0.04,3.21,525582771,-73557408.06,Desceu,CVC
80,GOLL4,2024-01-26,5.92,-0.08,6.44,198184909,-102993202.62,Desceu,GOL

In [77]:
df_principal = df_principal.merge(df_chatgpt, left_on='Nome', right_on='Nome da Empresa', how='left')
df_principal = df_principal.drop(columns='Nome da Empresa').copy()
df_principal

,Ativo,Data,valor_final,var_dia_pct,valor_inicial,Qtd_teorica,variacao_rs,Resultado,Nome,Segmento,Idade (anos)
0,USIM5,2024-01-26,9.50,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia e Metalurgia,62
1,CMIN3,2024-01-26,6.82,0.02,6.66,1110559345,177515970.30,Subiu,CSN Mineração,Mineração,78
2,PETR3,2024-01-26,41.96,0.02,41.06,2379877655,2140059393.53,Subiu,Petrobras,Petróleo e Gás,71
3,SUZB3,2024-01-26,52.91,0.02,51.85,683452836,722946282.71,Subiu,Suzano,Papel e Celulose,100
4,CPFE3,2024-01-26,37.10,0.02,36.36,187732538,138573955.06,Subiu,CPFL Energia,Energia,111
...,...,...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-0.02,10.98,533990587,-143635530.57,Desceu,Carrefour Brasil,Varejo,49
77,BHIA3,2024-01-26,8.70,-0.02,8.92,94843047,-20810240.84,Desceu,Casas Bahia,Varejo,72
78,RENT3,2024-01-26,56.24,-0.04,58.36,853202347,-1807432634.46,Desceu,Localiza,Locação de Veículos,51
79,CVCB3,2024-01-26,3.07,-0.04,3.21,525582771,-73557408.06,Desceu,CVC,Turismo,52
80,GOLL4,2024-01-26,5.92,-0.08,6.44,198184909,-102993202.62,Desceu,GOL,Aviação,24

In [78]:
df_principal = df_principal.rename(columns={'Idade (anos)':'Ano_de_fundacao'}).copy()
df_principal

,Ativo,Data,valor_final,var_dia_pct,valor_inicial,Qtd_teorica,variacao_rs,Resultado,Nome,Segmento,Ano_de_fundacao
0,USIM5,2024-01-26,9.50,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia e Metalurgia,62
1,CMIN3,2024-01-26,6.82,0.02,6.66,1110559345,177515970.30,Subiu,CSN Mineração,Mineração,78
2,PETR3,2024-01-26,41.96,0.02,41.06,2379877655,2140059393.53,Subiu,Petrobras,Petróleo e Gás,71
3,SUZB3,2024-01-26,52.91,0.02,51.85,683452836,722946282.71,Subiu,Suzano,Papel e Celulose,100
4,CPFE3,2024-01-26,37.10,0.02,36.36,187732538,138573955.06,Subiu,CPFL Energia,Energia,111
...,...,...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-0.02,10.98,533990587,-143635530.57,Desceu,Carrefour Brasil,Varejo,49
77,BHIA3,2024-01-26,8.70,-0.02,8.92,94843047,-20810240.84,Desceu,Casas Bahia,Varejo,72
78,RENT3,2024-01-26,56.24,-0.04,58.36,853202347,-1807432634.46,Desceu,Localiza,Locação de Veículos,51
79,CVCB3,2024-01-26,3.07,-0.04,3.21,525582771,-73557408.06,Desceu,CVC,Turismo,52
80,GOLL4,2024-01-26,5.92,-0.08,6.44,198184909,-102993202.62,Desceu,GOL,Aviação,24

In [79]:
df_principal['Cat_idade'] = df_principal['Ano_de_fundacao'].apply(lambda x: 'Mais de 100' if x > 100 else ('Menos de 50' if x < 50 else 'Entre 50 e 100'))
df_principal

,Ativo,Data,valor_final,var_dia_pct,valor_inicial,Qtd_teorica,variacao_rs,Resultado,Nome,Segmento,Ano_de_fundacao,Cat_idade
0,USIM5,2024-01-26,9.50,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia e Metalurgia,62,Entre 50 e 100
1,CMIN3,2024-01-26,6.82,0.02,6.66,1110559345,177515970.30,Subiu,CSN Mineração,Mineração,78,Entre 50 e 100
2,PETR3,2024-01-26,41.96,0.02,41.06,2379877655,2140059393.53,Subiu,Petrobras,Petróleo e Gás,71,Entre 50 e 100
3,SUZB3,2024-01-26,52.91,0.02,51.85,683452836,722946282.71,Subiu,Suzano,Papel e Celulose,100,Entre 50 e 100
4,CPFE3,2024-01-26,37.10,0.02,36.36,187732538,138573955.06,Subiu,CPFL Energia,Energia,111,Mais de 100
...,...,...,...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-0.02,10.98,533990587,-143635530.57,Desceu,Carrefour Brasil,Varejo,49,Menos de 50
77,BHIA3,2024-01-26,8.70,-0.02,8.92,94843047,-20810240.84,Desceu,Casas Bahia,Varejo,72,Entre 50 e 100
78,RENT3,2024-01-26,56.24,-0.04,58.36,853202347,-1807432634.46,Desceu,Localiza,Locação de Veículos,51,Entre 50 e 100
79,CVCB3,2024-01-26,3.07,-0.04,3.21,525582771,-73557408.06,Desceu,CVC,Turismo,52,Entre 50 e 100
80,GOLL4,2024-01-26,5.92,-0.08,6.44,198184909,-102993202.62,Desceu,GOL,Aviação,24,Menos de 50

Analises

In [80]:
# Calculando o maior valor
maior = df_principal['variacao_rs'].max()

# Calculando o menor valor
menor = df_principal['variacao_rs'].min()

# Calculando a média
media = df_principal['variacao_rs'].mean()

# Calculando a média de quem subiu
media_subiu = df_principal[df_principal['Resultado'] == 'Subiu']['variacao_rs'].mean()

# Calculando a média de quem desceu
media_desceu = df_principal[df_principal['Resultado'] == 'Desceu']['variacao_rs'].mean()

# Imprimindo os resultados
print(f"Maior\tR$ {maior:,.2f}")
print(f"Menor\tR$ {menor:,.2f}")
print(f"Média\tR$ {media:,.2f}")
print(f"Média de quem subiu\tR$ {media_subiu:,.2f}")
print(f"Média de quem desceu\tR$ {media_desceu:,.2f}")

Maior	R$ 4,762,926,995.25
Menor	R$ -1,807,432,634.46
Média	R$ 165,190,210.48
Média de quem subiu	R$ 448,164,250.23
Média de quem desceu	R$ -181,109,141.75

In [81]:
df_principal_subiu = df_principal[df_principal['Resultado'] == 'Subiu']
df_principal_subiu

,Ativo,Data,valor_final,var_dia_pct,valor_inicial,Qtd_teorica,variacao_rs,Resultado,Nome,Segmento,Ano_de_fundacao,Cat_idade
0,USIM5,2024-01-26,9.50,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia e Metalurgia,62,Entre 50 e 100
1,CMIN3,2024-01-26,6.82,0.02,6.66,1110559345,177515970.30,Subiu,CSN Mineração,Mineração,78,Entre 50 e 100
2,PETR3,2024-01-26,41.96,0.02,41.06,2379877655,2140059393.53,Subiu,Petrobras,Petróleo e Gás,71,Entre 50 e 100
3,SUZB3,2024-01-26,52.91,0.02,51.85,683452836,722946282.71,Subiu,Suzano,Papel e Celulose,100,Entre 50 e 100
4,CPFE3,2024-01-26,37.10,0.02,36.36,187732538,138573955.06,Subiu,CPFL Energia,Energia,111,Mais de 100
5,PRIO3,2024-01-26,45.69,0.02,44.80,800010734,709687498.18,Subiu,PetroRio,Petróleo e Gás,43,Menos de 50
6,PETR4,2024-01-26,39.96,0.02,39.28,4566445852,3103136291.22,Subiu,Petrobras,Petróleo e Gás,71,Entre 50 e 100
7,VALE3,2024-01-26,69.50,0.02,68.37,4196924316,4762926995.25,Subiu,Vale,Mineração,82,Entre 50 e 100
8,MULT3,2024-01-26,28.19,0.02,27.75,268505432,117732680.08,Subiu,Multiplan,Shopping Centers,50,Entre 50 e 100
9,ITUB4,2024-01-26,32.81,0.01,32.33,4801593832,2297591984.33,Subiu,Itaú Unibanco,Bancário,99,Entre 50 e 100
10,RDOR3,2024-01-26,27.56,0.01,27.17,1168230366,453917907.01,Subiu,Rede D'Or,Saúde e Hospitais,47,Menos de 50
11,BRKM5,2024-01-26,18.55,0.01,18.29,265877867,69054317.64,Subiu,Braskem,Química e Petroquímica,22,Menos de 50
12,AZUL4,2024-01-26,14.27,0.01,14.07,327593725,65452205.55,Subiu,Azul,Aviação,16,Menos de 50
13,RRRP3,2024-01-26,28.75,0.01,28.35,235665566,94204643.35,Subiu,3R Petroleum,Petróleo e Gás,14,Menos de 50
14,EQTL3,2024-01-26,35.32,0.01,34.85,1095587251,511671895.45,Subiu,Equatorial Energia,Energia,25,Menos de 50
15,CSNA3,2024-01-26,18.16,0.01,17.92,600865451,143220991.46,Subiu,Siderúrgica Nacional,Siderurgia e Metalurgia,78,Entre 50 e 100
16,YDUQ3,2024-01-26,19.77,0.01,19.52,289347914,72295838.99,Subiu,YDUQS,Educação,52,Entre 50 e 100
17,UGPA3,2024-01-26,28.31,0.01,27.95,1086411192,388705223.96,Subiu,Ultrapar,Distribuição de Combustíveis,86,Entre 50 e 100
18,MRVE3,2024-01-26,8.08,0.01,7.98,376187582,37525872.38,Subiu,MRV,Construção Civil,44,Menos de 50
19,ARZZ3,2024-01-26,57.91,0.01,57.25,62305891,41021792.09,Subiu,Arezzo,Vestuário e Calçados,51,Entre 50 e 100
20,BBDC4,2024-01-26,15.52,0.01,15.36,5146576868,822148336.41,Subiu,Banco Bradesco,Bancário,81,Entre 50 e 100
21,BEEF3,2024-01-26,7.19,0.01,7.12,261036182,18214628.10,Subiu,Minerva,Alimentício,101,Mais de 100
22,PCAR3,2024-01-26,4.14,0.01,4.10,159430826,6340916.22,Subiu,Grupo Pão de Açúcar,Varejo,76,Entre 50 e 100
23,BRFS3,2024-01-26,14.61,0.01,14.47,1677525446,233045769.57,Subiu,BRF,Alimentício,85,Entre 50 e 100
24,VIVT3,2024-01-26,51.20,0.01,50.75,423091712,188965307.06,Subiu,Vivo,Telecomunicações,21,Menos de 50
25,RAIL3,2024-01-26,22.64,0.01,22.45,1218352541,229771333.63,Subiu,Rumo,Logística e Transportes,26,Menos de 50
26,CIEL3,2024-01-26,4.90,0.01,4.86,1095462329,43657683.38,Subiu,Cielo,Meios de Pagamento,28,Menos de 50
27,DXCO3,2024-01-26,7.81,0.01,7.75,302768240,18068446.61,Subiu,Dexco,Construção Civil,74,Entre 50 e 100
28,TIMS3,2024-01-26,17.52,0.01,17.39,807896814,103972807.37,Subiu,TIM,Telecomunicações,28,Menos de 50
29,BRAP4,2024-01-26,23.22,0.01,23.05,251003438,42238249.54,Subiu,Bradespar,Bancário/Investimentos,23,Menos de 50
30,LWSA3,2024-01-26,5.55,0.01,5.51,393173139,15598886.65,Subiu,Locaweb,Tecnologia e Internet,26,Menos de 50
31,RECV3,2024-01-26,23.83,0.01,23.66,275005663,46201006.00,Subiu,PetroRecôncavo,Petróleo e Gás,26,Menos de 50
32,ITSA4,2024-01-26,10.01,0.01,9.94,5372783971,373853994.88,Subiu,Itaúsa,Bancário/Investimentos,49,Menos de 50
33,BBAS3,2024-01-26,56.97,0.01,56.59,1420949112,546752087.99,Subiu,Banco do Brasil,Bancário,215,Mais de 100
34,RADL3,2024-01-26,26.16,0.01,26.00,1275798515,202352473.74,Subiu,RaiaDrogasil,Saúde/Farmácias,123,Mais de 100
35,GOAU4,2024-01-26,10.08,0.01,10.02,660411219,39045606.94,Subiu,Metalúrgica Gerdau,Siderurgia e Metalurgia,123,Mais de 100
36,CSAN3,2024-01-26,18.57,0.01,18.46,1168097881,127229653.18,Subiu,Cosan,Energia e Logística,89,Entre 50 e 100
37,JBSS3,2024-01-26,24.34,0.01,24.20,1134986472,156573285.43,Subiu,JBS,Alimentício,71,Entre 50 e 100
38,MGLU3,2024-01-26,2.08,0.00,2.07,2867627068,28493619.27,Subiu,Magazine Luiza,Varejo,67,Entre 50 e 100
39,BBDC3,2024-01-26,13.75,0.00,13.70,1500728902,74019610.05,Subiu,Banco Bradesco,Bancário,81,Entre 50 e 100
40,GGBR4,2024-01-26,21.84,0.00,21.78,1118525506,65779607.10,Subiu,Gerdau,Siderurgia e Metalurgia,123,Mais de 100
41,RAIZ4,2024-01-26,3.74,0.00,3.73,1193047233,11571106.42,Subiu,Raízen,Energia,14,Menos de 50
42,CPLE6,2024-01-26,10.07,0.00,10.05,1679335290,32069789.50,Subiu,Copel,Energia,70,Entre 50 e 100
43,VAMO3,2024-01-26,8.18,0.00,8.17,421383330,4131341.16,Subiu,Grupo Vamos,Logística e Transportes,10,Menos de 50

In [82]:
df_analise_segmento = df_principal_subiu.groupby('Segmento')['variacao_rs'].sum().reset_index()
df_analise_segmento

                        Segmento   variacao_rs
0                    Alimentício  407833683.09
1                        Aviação   65452205.55
2                       Bancário 3740512018.78
3         Bancário/Investimentos  416092244.42
4               Construção Civil   55594318.99
5   Distribuição de Combustíveis  388705223.96
6                       Educação   72295838.99
7                        Energia  693886746.43
8            Energia e Logística  127229653.18
9        Logística e Transportes  233902674.79
10            Meios de Pagamento   43657683.38
11                     Mineração 4940442965.55
12              Papel e Celulose  722946282.71
13                Petróleo e Gás 6093288832.26
14        Química e Petroquímica   69054317.64
15             Saúde e Hospitais  453917907.01
16               Saúde/Farmácias  202352473.74
17              Shopping Centers  117732680.08
18       Siderurgia e Metalurgia  489935930.93
19         Tecnologia e Internet   15598886.65
20              Telecomunicações  292938114.42
21                        Varejo   34834535.50
22          Vestuário e Calçados   41021792.09

In [83]:
df_analise_saldo = df_principal.groupby('Resultado')['variacao_rs'].sum().reset_index()
df_analise_saldo

  Resultado    variacao_rs
0    Desceu -6338819961.32
1   Estável           0.00
2     Subiu 19719227010.14

Criando grafico

In [84]:
fig = px.bar(df_analise_saldo, x='Resultado', y='variacao_rs', text='variacao_rs', title='Variação Reais por Resultado')
fig.show()

In [85]:
fig.update_traces(texttemplate="%{y:.2s}", textposition="outside")
fig.show()

In [86]:
# Função para formatar os valores corretamente, incluindo números negativos
def formatar_valor(valor):
    abs_valor = abs(valor)  # Obtém o valor absoluto para comparação

    if abs_valor >= 1_000_000_000:
        return f"{valor / 1_000_000_000:.2f}B"  # Bilhões
    elif abs_valor >= 1_000_000:
        return f"{valor / 1_000_000:.2f}M"  # Milhões
    elif abs_valor >= 1_000:
        return f"{valor / 1_000:.2f}K"  # Milhares
    else:
        return f"{valor:.2f}"  # Valor normal

# Criando uma nova coluna com os valores formatados para rótulos
# Using df_analise_saldo instead of df and 'variacao_rs' instead of 'Valor'
df_analise_saldo["Valor_Formatado"] = df_analise_saldo["variacao_rs"].apply(formatar_valor)

# Criando o gráfico
# Using df_analise_saldo instead of df and appropriate column names
fig = px.bar(df_analise_saldo, x="Resultado", y="variacao_rs", text=df_analise_saldo["Valor_Formatado"])  # Usa a coluna formatada para os rótulos

# Posiciona os rótulos acima das barras
fig.update_traces(textposition="outside")

fig.show()

In [87]:
fig = px.pie(df_analise_segmento, names='Segmento', values='variacao_rs', title='Variação Reais por Segmento')
fig.show()

In [94]:
df_analise_cat_idade = df_principal.groupby('Cat_idade')['variacao_rs'].sum().reset_index() # Creating the DataFrame
#Now use it

In [95]:

fig = px.bar(df_analise_cat_idade,
             x='Cat_idade', # Changed 'cat_idade' to 'Cat_idade'
             y='variacao_rs',
             text='variacao_rs',
             title='Variação Reais por Categoria de Idade')
fig.show()

In [96]:
# Função para formatar os valores corretamente, incluindo números negativos
def formatar_valor(valor):
    abs_valor = abs(valor)  # Obtém o valor absoluto para comparação

    if abs_valor >= 1_000_000_000:
        return f"{valor / 1_000_000_000:.2f}B"  # Bilhões
    elif abs_valor >= 1_000_000:
        return f"{valor / 1_000_000:.2f}M"  # Milhões
    elif abs_valor >= 1_000:
        return f"{valor / 1_000:.2f}K"  # Milhares
    else:
        return f"{valor:.2f}"  # Valor normal

# Criando uma nova coluna com os valores formatados para rótulos
df_analise_cat_idade["Valor_Formatado"] = df_analise_cat_idade["variacao_rs"].apply(formatar_valor)

# Criando o gráfico com os rótulos formatados corretamente
fig = px.bar(df_analise_cat_idade, x="Cat_idade", y="variacao_rs", text=df_analise_cat_idade["Valor_Formatado"])

# Posiciona os rótulos acima das barras
fig.update_traces(textposition="outside")

# Exibe o gráfico
fig.show()